### ISSUE TITLE
Axios with Android

### ISSUE THREAD

**Issue by baranonen** [baranonen/SSALConnect#1]
Axios is not fetching or showing images on Android (there's no problem on iOS)

**Comment by bgrgndzz** [comment]
Hatalı kodu atar mısın bir bakayım

**Comment by baranonen** [comment]
@bgrgndzz ./src/components/Liste.js'de axios ve render kısmı var, Detay.js'de ise containerlar var.

**Comment by bgrgndzz** [comment]
`url` yerine `uri` yazman gerekiyor, [dokümentasyondan daha fazla bilgi alabilirsin.](https://facebook.github.io/react-native/docs/image)

**Comment by baranonen** [comment]
@bgrgndzz Teşekkür ederim, bir dahaki commit’e ekleyeceğim.
